services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
      
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_started
    deploy:
      replicas: 3
    command: sh -c "celery -A app.celery_app worker --loglevel=info --pool=solo"

  celery-beat:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: sh -c "celery -A app.celery_app beat --loglevel=info"

  flower:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - worker
      - celery-beat
    command: sh -c "celery -A app.celery_app flower --port=5555 --address=0.0.0.0"
    

volumes:
  redis_data: